name: ASP
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.9
- pytorch==1.12.1
- torchvision==0.13.1
- cudatoolkit=11.6
- scipy
- dominate
- torchvision
- opencv
- Pillow
- numpy
- visdom
- packaging
- GPUtil
